server:
  port: 8080

spring: # general spring settings
  h2:
    console:
      enabled: true
  application:
    name: backend-business # application name
  datasource:
    ## url:                   jdbc:postgresql://localhost:5432/
    url:                   jdbc:h2:file:./test
    username:              sa
    password:
  jpa:
    hibernate:
      ddl-auto:            none
    properties:
      hibernate:
        ## dialect:           org.hibernate.dialect.PostgreSQLDialect
        dialect:           org.hibernate.dialect.H2Dialect
        jdbc:
#  liquibase:
#    enabled:               false
#    rollbackFile:          "liquibase-rollback-file.sql"
